/* Nexus ERP — Accounting Core Extension (Mandatory accounting features)
   Adds: Fiscal periods & locking, hierarchical Chart of Accounts, document number sequences,
         journal approval workflow, fixed assets & depreciation, bank reconciliation,
         cost centers, closing entries, cash flow statement. */
'use strict';
/* ============================ FISCAL PERIODS ============================ */
function fiscalYearStart(){ const s=DB.getOne('settings')||{}; return s.fyStart || (new Date().getFullYear()+'-01-01'); }
function getPeriods(){ return DB.get('periods'); }
function ensurePeriods(){
  let periods=DB.get('periods');
  if(periods.length) return;
  const start=new Date(fiscalYearStart()); const out=[];
  for(let m=0;m<12;m++){ const d=new Date(start.getFullYear(),start.getMonth()+m,1); const ym=d.toISOString().slice(0,7);
    out.push({id:'per_'+ym, code:ym, label:t('شهر','Month')+' '+ym, start:ym+'-01', end:new Date(d.getFullYear(),d.getMonth()+1,0).toISOString().slice(0,10), status:'open', closedAt:null}); }
  DB.set('periods',out);
}
function getPeriodStatus(ym){ const p=DB.get('periods').find(x=>x.code===ym); return p?p.status:'open'; }
function isPeriodLocked(ym){ return getPeriodStatus(ym)!=='open'; }
function periodOf(iso){ return (iso||'').slice(0,7); }
function lockPeriod(ym){ const periods=DB.get('periods'); const p=periods.find(x=>x.code===ym); if(!p) return; if(reportTrialBalanceRows(ym).unbalanced){ toast(t('لا يمكن قفل فترة غير متوازنة','Cannot lock unbalanced period')); return; } p.status='closed'; p.closedAt=nowISO(); DB.set('periods',periods); logAudit(t('قفل فترة','Lock period'),ym); toast(t('تم قفل الفترة','Period locked')+' '+ym); }
function openPeriod(ym){ const periods=DB.get('periods'); const p=periods.find(x=>x.code===ym); if(!p) return; p.status='open'; p.closedAt=null; DB.set('periods',periods); logAudit(t('فتح فترة','Open period'),ym); toast(t('تم فتح الفترة','Period opened')+' '+ym); }
function renderPeriodsScreen(){ ensurePeriods(); $('#screen').innerHTML=`<div class="screen"><div class="toolbar"><h2>${t('الفترات المحاسبية','Fiscal Periods')}</h2></div>
  <table class="tbl"><thead><tr><th>${t('الفترة','Period')}</th><th>${t('من','From')}</th><th>${t('إلى','To')}</th><th>${t('الحالة','Status')}</th><th></th></tr></thead><tbody>${DB.get('periods').map(p=>`<tr><td>${esc(p.code)}</td><td>${fmtDate(p.start)}</td><td>${fmtDate(p.end)}</td><td>${p.status==='closed'?t('مقفلة','Closed'):t('مفتوحة','Open')}</td><td>${p.status==='closed'?`<button class="btn" onclick="openPeriod('${p.code}')">${t('فتح','Open')}</button>`:`<button class="btn btn-danger" onclick="lockPeriod('${p.code}')">${t('قفل','Lock')}</button>`}</td></tr>`).join('')}</tbody></table>
  <p class="muted">${t('الفترة المقفلة لا يمكن تعديل قيودها أو مستنداتها','A closed period cannot be edited')}</p></div>`; applyLang(); }
/* ============================ NUMBER SEQUENCES ============================ */
function nextNumber(key, prefix, pad){ ensureSeq(); const s=DB.getOne('seq')||{}; s[key]=s[key]||{value:0,prefix,pad:pad||4}; s[key].value++; DB.setOne('seq',s); const v=String(s[key].value).padStart(s[key].pad,'0'); return s[key].prefix+v; }
function currentNumber(key){ const s=DB.getOne('seq')||{}; return (s[key]&&(s[key].prefix+String(s[key].value).padStart(s[key].pad||4,'0'))); }
function ensureSeq(){ if(!DB.getOne('seq')){ DB.setOne('seq',{INV:{value:0,prefix:'INV-',pad:6},PU:{value:0,prefix:'PU-',pad:6},PO:{value:0,prefix:'PO-',pad:6},RET:{value:0,prefix:'R-',pad:6},JV:{value:0,prefix:'JV-',pad:5},PAY:{value:0,prefix:'PAY-',pad:5},REC:{value:0,prefix:'REC-',pad:5},FA:{value:0,prefix:'FA-',pad:4}}); } }
function renderSeqScreen(){ ensureSeq(); const s=DB.getOne('seq')||{}; $('#screen').innerHTML=`<div class="screen"><div class="toolbar"><h2>${t('تسلسل المستندات','Document Sequences')}</h2></div>
  <table class="tbl"><thead><tr><th>${t('النوع','Type')}</th><th>${t('الحالي','Current')}</th></tr></thead><tbody>${Object.keys(s).map(k=>`<tr><td>${esc(k)}</td><td>${esc(s[k].prefix+String(s[k].value).padStart(s[k].pad,'0'))}</td></tr>`).join('')}</tbody></table>
  <button class="btn btn-danger" onclick="resetSequences()">${t('إعادة ضبط العدادات','Reset counters')}</button></div>`; applyLang(); }
function resetSequences(){ confirmModal(t('تأكيد','Confirm'), t('إعادة ضبط عدادات التسلسل؟','Reset sequence counters?'), ()=>{ DB.remove('seq'); ensureSeq(); renderSeqScreen(); toast(t('تم الضبط','Reset')); }); }
/* ============================ HIERARCHICAL CHART OF ACCOUNTS ============================ */
function renderAccountsScreen(){ ensureAccountTypes(); const accounts=DB.get('accounts'); const balances=computeBalances();
  function row(a,depth){ const children=accounts.filter(x=>x.parent===a.id); let html=`<tr><td>${esc(a.code)}</td><td style="padding-inline-start:${8+depth*18}px">${esc(a.name)}</td><td>${t(a.type,a.type)}</td><td>${money(balances[a.id]||0)}</td><td><button class="btn sm" onclick="openAccountModal('${a.id}')">${t('تعديل','Edit')}</button></td></tr>`; children.forEach(c=>{ html+=row(c,depth+1); }); return html; }
  const roots=accounts.filter(a=>!a.parent);
  $('#screen').innerHTML=`<div class="screen"><div class="toolbar"><h2>${t('دليل الحسابات','Chart of Accounts')}</h2><button class="btn btn-primary" onclick="openAccountModal()">${t('حساب جديد','New Account')}</button></div>
  <table class="tbl"><thead><tr><th>${t('الكود','Code')}</th><th>${t('الحساب','Account')}</th><th>${t('النوع','Type')}</th><th>${t('الرصيد','Balance')}</th><th></th></tr></thead><tbody>${roots.map(r=>row(r,0)).join('')||`<tr><td colspan="5">${t('لا حسابات','No accounts')}</td></tr>`}</tbody></table></div>`; applyLang(); }
function ensureAccountTypes(){ /* account.type stays as-is; types are fixed set */ }
function openAccountModal(parentId){ const edit=parentId&&DB.get('accounts').find(x=>x.id===parentId)?DB.get('accounts').find(x=>x.id===parentId):null; const isEdit=!!edit&&edit.parent!==undefined&&arguments.length===1&&DB.get('accounts').find(x=>x.id===parentId);
  openModal(t('حساب','Account'), `<div class="form-grid"><label>${t('الاسم','Name')}<input id="acName" value="${esc(edit?edit.name:'')}"></label><label>${t('الكود','Code')}<input id="acCode" value="${esc(edit?edit.code:'')}"></label><label>${t('النوع','Type')}<select id="acType">${['asset','liability','income','expense','equity'].map(ty=>`<option value="${ty}" ${edit&&edit.type===ty?'selected':''}>${t(ty,ty)}</option>`).join('')}</select></label><label>${t('تحت حساب','Parent')}<select id="acParent"><option value="">—</option>${DB.get('accounts').filter(a=>!edit||a.id!==edit.id).map(a=>`<option value="${a.id}" ${edit&&edit.parent===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label></div>`, [{label:t('حفظ','Save'),cls:'btn-primary',onClick:()=>{ const name=$('#acName').value.trim(); if(!name){toast(t('الاسم مطلوب','Name required'));return;} const list=DB.get('accounts'); const obj={name,code:$('#acCode').value||(''+list.length),type:$('#acType').value,parent:$('#acParent').value||null,balance:0}; if(edit){ Object.assign(edit,obj); } else list.push(Object.assign({id:uid()},obj)); DB.set('accounts',list); closeModal(); renderAccountsScreen(); }},{label:t('إلغاء','Cancel'),cls:'btn',onClick:closeModal}]); }
/* ============================ JOURNAL APPROVAL WORKFLOW ============================ */
/* status: draft -> pending (submitted) -> approved (posted) ; rejected -> draft */
function postJournalEntry(j){ j.status='approved'; j.postedAt=nowISO(); j.postedBy=(currentUser&&currentUser.name)||t('النظام','System'); DB.set('journal',DB.get('journal')); }
function submitJournal(id){ const J=DB.get('journal'); const j=J.find(x=>x.id===id); if(!j) return; if(!isJournalBalanced(j)){ toast(t('القيد غير متوازن','Unbalanced entry')); return; } j.status='pending'; j.submittedAt=nowISO(); DB.set('journal',J); renderJournalScreen(); }
function approveJournal(id){ const J=DB.get('journal'); const j=J.find(x=>x.id===id); if(!j) return; if(isPeriodLocked(periodOf(j.date))){ toast(t('الفترة مقفلة','Period locked')); return; } j.status='approved'; j.approvedAt=nowISO(); j.approvedBy=(currentUser&&currentUser.name)||t('النظام','System'); DB.set('journal',J); logAudit(t('اعتماد قيد','Approve JV'),j.code||''); renderJournalScreen(); }
function rejectJournal(id){ const J=DB.get('journal'); const j=J.find(x=>x.id===id); if(!j) return; j.status='draft'; j.rejectedAt=nowISO(); DB.set('journal',J); renderJournalScreen(); }
function isJournalBalanced(j){ const d=DEC.sum(j.lines, 'debit'); const c=DEC.sum(j.lines, 'credit'); return DEC.eq(d, c); }
function openJournalModal(){ const accounts=DB.get('accounts'); openModal(t('قيد يومية','Journal Entry'), `<div class="form-grid"><label>${t('البيان','Desc')}<input id="jDesc"></label><label>${t('التاريخ','Date')}<input id="jDate" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>${t('مركز التكلفة','Cost Center')}<select id="jCC"><option value="">—</option>${DB.get('costCenters').map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label></div><div id="jLines"></div><button class="btn" onclick="addJLine()">${t('إضافة سطر','Add line')}</button><div id="jCheck"></div>`, [{label:t('حفظ كمسودة','Save Draft'),cls:'btn',onClick:()=>saveJournal('draft')},{label:t('اعتماد مباشر','Post'),cls:'btn-primary',onClick:()=>saveJournal('approved')},{label:t('إلغاء','Cancel'),cls:'btn',onClick:closeModal}]); $('#jLines').innerHTML=''; addJLine(); addJLine(); }
function addJLine(){ const row=document.createElement('div'); row.className='v-row'; row.innerHTML=`<select data-a>${DB.get('accounts').map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select><input data-d type="number" placeholder="${t('مدين','Debit')}" value="0"><input data-c type="number" placeholder="${t('دائن','Credit')}" value="0" onchange="jCheck()">`; $('#jLines').appendChild(row); jCheck(); }
function jCheck(){ let d=0,c=0; $$('#jLines .v-row').forEach(r=>{ d=DEC.add(d, Number(r.querySelector('[data-d]').value)||0); c=DEC.add(c, Number(r.querySelector('[data-c]').value)||0); }); $('#jCheck').innerHTML=`<div>${t('مدين','Debit')}: ${money(d)} | ${t('دائن','Credit')}: ${money(c)} ${DEC.eq(d,c)?'✅':''}</div>`; }
function saveJournal(status){ const lines=$$('#jLines .v-row').map(r=>({accountId:r.querySelector('[data-a]').value,debit:Number(r.querySelector('[data-d]').value)||0,credit:Number(r.querySelector('[data-c]').value)||0,costCenter:$('#jCC').value||null})); if(!lines.length||lines.every(l=>!l.debit&&!l.credit)){ toast(t('أدخل سطراً','Enter a line')); return; }   const vres=Validate.schema({date:{type:'date',notFuture:true,label:t('التاريخ','Date')}}, $('#jDate').value?{date:$('#jDate').value}:{}); if(!Validate.report(vres)) return; if(!DEC.eq(DEC.sum(lines,'debit'), DEC.sum(lines,'credit'))){ toast(t('القيد غير متوازن','Unbalanced')); return; } const code=nextNumber('JV','JV-',5); const j={id:uid(),code,date:$('#jDate').value,desc:$('#jDesc').value,costCenter:$('#jCC').value||null,lines:normalizeLines(lines),ref:null,status:status==='approved'?'approved':'draft',createdAt:nowISO(),createdBy:(currentUser&&currentUser.name)||t('النظام','System')}; const J=DB.get('journal'); J.push(j); DB.set('journal',J); logAudit(t('قيد يومية','Journal'),code+' '+(status==='approved'?t('معتمد','approved'):t('مسودة','draft'))); closeModal(); renderJournalScreen(); }
function renderJournalScreen(){ const J=DB.get('journal'); $('#screen').innerHTML=`<div class="screen"><div class="toolbar"><h2>${t('القيود اليومية','Journal Entries')}</h2><button class="btn btn-primary" onclick="openJournalModal()">${t('قيد جديد','New Entry')}</button></div>
  <table class="tbl"><thead><tr><th>${t('الكود','Code')}</th><th>${t('التاريخ','Date')}</th><th>${t('البيان','Desc')}</th><th>${t('الحالة','Status')}</th><th></th></tr></thead><tbody>${J.slice().reverse().map(j=>`<tr><td>${esc(j.code)}</td><td>${fmtDate(j.date)}</td><td>${esc(j.desc)}</td><td>${j.status==='approved'?t('معتمد','Approved'):j.status==='pending'?t('بالانتظار','Pending'):t('مسودة','Draft')}</td><td>${j.status==='draft'?`<button class="btn sm" onclick="submitJournal('${j.id}')">${t('إرسال','Submit')}</button>`:''}${j.status==='pending'?`<button class="btn sm btn-primary" onclick="approveJournal('${j.id}')">${t('اعتماد','Approve')}</button> <button class="btn sm" onclick="rejectJournal('${j.id}')">${t('رفض','Reject')}</button>`:''} <button class="btn sm" onclick="viewJournal('${j.id}')">${t('عرض','View')}</button></td></tr>`).join('')}</tbody></table></div>`; applyLang(); }
function viewJournal(id){ const j=DB.get('journal').find(x=>x.id===id); if(!j) return; const accounts=DB.get('accounts'); const rows=j.lines.map(l=>`<tr><td>${esc((accounts.find(a=>a.id===l.accountId)||{}).name||'')}</td><td>${fmt(l.debit)}</td><td>${fmt(l.credit)}</td></tr>`).join(''); openModal(esc(j.code), `<p>${esc(j.desc)} · ${fmtDate(j.date)} · ${j.status}</p><table class="tbl"><thead><tr><th>${t('الحساب','Account')}</th><th>${t('مدين','Debit')}</th><th>${t('دائن','Credit')}</th></tr></thead><tbody>${rows}</tbody></table>`, [{label:t('إغلاق','Close'),cls:'btn',onClick:closeModal}]); }
/* ============================ FIXED ASSETS & DEPRECIATION ============================ */
function renderAssetsScreen(){ ensureAssetAccount(); const assets=DB.get('assets'); $('#screen').innerHTML=`<div class="screen"><div class="toolbar"><h2>${t('الأصول الثابتة','Fixed Assets')}</h2><button class="btn btn-primary" onclick="openAssetModal()">${t('أصل جديد','New Asset')}</button><button class="btn" onclick="runDepreciationAll()">${t('إهلاك الكل','Depreciate All')}</button></div>
  <table class="tbl"><thead><tr><th>${t('الكود','Code')}</th><th>${t('الاسم','Name')}</th><th>${t('التكلفة','Cost')}</th><th>${t('القيمة الدفترية','NBV')}</th><th>${t('الإهلاك المتراكم','Acc.Dep')}</th><th></th></tr></thead><tbody>${assets.map(a=>`<tr><td>${esc(a.code)}</td><td>${esc(a.name)}</td><td>${money(a.cost)}</td><td>${money(a.cost-(a.accDep||0))}</td><td>${money(a.accDep||0)}</td><td><button class="btn sm" onclick="openAssetModal('${a.id}')">${t('تعديل','Edit')}</button> <button class="btn sm" onclick="runDepreciation('${a.id}')">${t('إهلاك','Dep')}</button></td></tr>`).join('')}</tbody></table></div>`; applyLang(); }
function ensureAssetAccount(){ let a=DB.get('accounts').find(x=>x.id==='acc_fa'); if(!a){ const list=DB.get('accounts'); list.push({id:'acc_fa',code:'1201',name:t('الأصول الثابتة','Fixed Assets'),type:'asset',parent:'acc_asset_root',balance:0}); DB.set('accounts',list); } let d=DB.get('accounts').find(x=>x.id==='acc_fa_dep'); if(!d){ const list=DB.get('accounts'); list.push({id:'acc_fa_dep',code:'1202',name:t('مجمع الإهلاك','Accumulated Depreciation'),type:'asset',parent:'acc_asset_root',balance:0}); DB.set('accounts',list); } }
function openAssetModal(id){ const a=id?DB.get('assets').find(x=>x.id===id):null; openModal(t('أصل ثابت','Fixed Asset'), `<div class="form-grid"><label>${t('الاسم','Name')}<input id="faName" value="${esc(a?a.name:'')}"></label><label>${t('الكود','Code')}<input id="faCode" value="${esc(a?a.code:'')}"></label><label>${t('التكلفة','Cost')}<input id="faCost" type="number" value="${a?a.cost:0}"></label><label>${t('العمر الإنتاجي (سنة)','Useful Life')}<input id="faLife" type="number" value="${a?a.life:5}"></label><label>${t('طريقة الإهلاك','Method')}<select id="faMethod"><option value="straight" ${a&&a.method==='straight'?'selected':''}>${t('قسط ثابت','Straight Line')}</option><option value="declining" ${a&&a.method==='declining'?'selected':''}>${t('رصيد متناقص','Declining')}</option></select></label><label>${t('تاريخ الشراء','Purchase Date')}<input id="faDate" type="date" value="${a?a.date:new Date().toISOString().slice(0,10)}"></label></div>`, [{label:t('حفظ','Save'),cls:'btn-primary',onClick:()=>{ const name=$('#faName').value.trim(); if(!name){toast(t('الاسم مطلوب','Name required'));return;} const list=DB.get('assets'); const obj={name,code:$('#faCode').value||nextNumber('FA','FA-',4),cost:Number($('#faCost').value)||0,life:Number($('#faLife').value)||1,method:$('#faMethod').value,date:$('#faDate').value,accDep:a?a.accDep||0:0,lastDep:a?a.lastDep:null}; if(a) Object.assign(a,obj); else list.push(Object.assign({id:uid()},obj)); DB.set('assets',list); closeModal(); renderAssetsScreen(); }},{label:t('إلغاء','Cancel'),cls:'btn',onClick:closeModal}]); }
function depreciationForMonth(a){ if(a.method==='straight'){ return a.cost/a.life/12; } else { const nbv=a.cost-(a.accDep||0); return nbv*(2/a.life)/12; } }
function runDepreciation(id){ const assets=DB.get('assets'); const a=assets.find(x=>x.id===id); if(!a) return; const ym=new Date().toISOString().slice(0,7); if(a.lastDepMonth===ym){ toast(t('تم إهلاك هذا الشهر','Already depreciated this month')+' '+esc(a.name)); return; } if(isPeriodLocked(ym)){ toast(t('الفترة مقفلة','Period locked')); return; } const nbv=a.cost-(a.accDep||0); if(nbv<=0){ toast(t('قيمة الأصل صفر','Asset value zero')); return; } let dep=depreciationForMonth(a); if(dep>nbv) dep=nbv; a.accDep=(a.accDep||0)+dep; a.lastDep=nowISO(); a.lastDepMonth=ym; DB.set('assets',assets);   const J=DB.get('journal'); const d=new Date().toISOString().slice(0,10); J.push({id:uid(),code:nextNumber('JV','JV-',5),date:d,desc:t('إهلاك','Depreciation')+' '+a.name,lines:normalizeLines([{accountId:CFG.ACC.DEPRECIATION_EXP,debit:DEC.round(dep),credit:0},{accountId:CFG.ACC.FA_DEP,debit:0,credit:DEC.round(dep)}]),ref:a.id,status:'approved'}); DB.set('journal',J); logAudit(t('إهلاك أصل','Asset depreciation'),a.name+' '+money(dep)); renderAssetsScreen(); toast(t('تم الإهلاك','Depreciated')+' '+money(dep)); }
function runDepreciationAll(){ const ym=new Date().toISOString().slice(0,7); if(isPeriodLocked(ym)){ toast(t('الفترة مقفلة','Period locked')); return; } const ids=DB.get('assets').map(a=>a.id); let n=0; ids.forEach(id=>{ const a=DB.get('assets').find(x=>x.id===id); if(a && (a.cost-(a.accDep||0))>0 && a.lastDepMonth!==ym){ runDepreciation(id); if(DB.get('assets').find(x=>x.id===id).lastDepMonth===ym) n++; } }); toast(t('تم إهلاك','Depreciated')+' '+n); }
/* ============================ BANK RECONCILIATION ============================ */
function renderReconcileScreen(){ const banks=DB.get('bankAccounts'); $('#screen').innerHTML=`<div class="screen"><div class="toolbar"><h2>${t('التسوية البنكية','Bank Reconciliation')}</h2></div>
  <div id="recWrap">${banks.length?banks.map(b=>`<div class="kpi"><span>${esc(b.name)}</span><b>${money(b.balance)}</b><button class="btn sm" onclick="openReconcile('${b.id}')">${t('تسوية','Reconcile')}</button></div>`).join(''):`<p>${t('لا حسابات بنكية','No bank accounts')}</p>`}</div></div>`; applyLang(); }
function openReconcile(bankId){ const b=DB.get('bankAccounts').find(x=>x.id===bankId); if(!b) return; const statements=DB.get('bankStatements').filter(s=>s.bankId===bankId); const book=computeBalances()[b.accountId]||0; openModal(t('تسوية بنكية','Reconcile')+' '+esc(b.name), `<p>${t('رصيد الدفتر (حسب القيود)','Book Balance')}: <b>${money(book)}</b></p><label>${t('كشف البنك (الرصيد النهائي)','Bank Statement Balance')}<input id="stmtBal" type="number" value="${b.statementBal||book}"></label><div id="stmtRows"></div><button class="btn" onclick="addStmtRow('${bankId}')">${t('إضافة بند','Add Item')}</button><div id="stmtSum"></div>`, [{label:t('حفظ','Save'),cls:'btn-primary',onClick:()=>{ const bal=Number($('#stmtBal').value)||0; const rows=$$('#stmtRows .tx-row').map(r=>({date:r.querySelector('[data-d]').value,desc:r.querySelector('[data-desc]').value,amount:Number(r.querySelector('[data-amt]').value)||0,cleared:r.querySelector('[data-cl]').checked})); const list=DB.get('bankStatements'); list.push({id:uid(),bankId,balance:bal,rows,date:new Date().toISOString().slice(0,10),bookBalance:book}); DB.set('bankStatements',list); b.statementBal=bal; DB.set('bankAccounts',DB.get('bankAccounts')); const diff=bal-book; $('#stmtSum').innerHTML=`<p>${t('رصيد الدفتر','Book')}: ${money(book)}</p><p>${t('رصيد البنك','Bank')}: ${money(bal)}</p><p><b>${t('الفرق','Difference')}: ${money(diff)}</b></p>`; if(Math.abs(diff)<0.01) toast(t('متطابق','Reconciled')); else toast(t('يوجد فرق','Difference exists')); closeModal(); renderReconcileScreen(); }},{label:t('إلغاء','Cancel'),cls:'btn',onClick:closeModal}]);
  $('#stmtRows').innerHTML=(statements[0]?statements[0].rows:[]).map(r=>`<div class="tx-row"><input data-d type="date" value="${esc(r.date||'')}"><input data-desc placeholder="${t('البيان','Desc')}" value="${esc(r.desc||'')}"><input data-amt type="number" value="${r.amount||0}"><input type="checkbox" data-cl ${r.cleared?'checked':''}> ${t('مطابق','Cleared')}</div>`).join(''); }
function addStmtRow(){ const wrap=$('#stmtRows'); const row=document.createElement('div'); row.className='tx-row'; row.innerHTML=`<input data-d type="date"><input data-desc placeholder="${t('البيان','Desc')}"><input data-amt type="number" value="0"><input type="checkbox" data-cl> ${t('مطابق','Cleared')}`; wrap.appendChild(row); }
/* ============================ COST CENTERS ============================ */
function renderCostCentersScreen(){ const list=DB.get('costCenters'); $('#screen').innerHTML=`<div class="screen"><div class="toolbar"><h2>${t('مراكز التكلفة','Cost Centers')}</h2><button class="btn btn-primary" onclick="openCostCenterModal()">${t('مركز جديد','New')}</button></div>
  <table class="tbl"><thead><tr><th>${t('الكود','Code')}</th><th>${t('الاسم','Name')}</th><th></th></tr></thead><tbody>${list.map(c=>`<tr><td>${esc(c.code)}</td><td>${esc(c.name)}</td><td><button class="btn sm" onclick="openCostCenterModal('${c.id}')">${t('تعديل','Edit')}</button> <button class="btn sm btn-danger" onclick="deleteCostCenter('${c.id}')">${t('حذف','Delete')}</button></td></tr>`).join('')}</tbody></table>
  <h3>${t('تقرير مراكز التكلفة','Cost Center Report')}</h3><table class="tbl"><thead><tr><th>${t('مركز التكلفة','Cost Center')}</th><th>${t('مدين','Debit')}</th><th>${t('دائن','Credit')}</th></tr></thead><tbody>${costCenterTotals().map(r=>`<tr><td>${esc(r.name)}</td><td>${money(r.debit)}</td><td>${money(r.credit)}</td></tr>`).join('')}</tbody></table></div>`; applyLang(); }
function costCenterTotals(){ const ccs=DB.get('costCenters'); const map={}; ccs.forEach(c=>map[c.id]={name:c.name,debit:0,credit:0}); DB.get('journal').forEach(j=>j.lines.forEach(l=>{ if(l.costCenter&&map[l.costCenter]){ map[l.costCenter].debit+=l.debit||0; map[l.costCenter].credit+=l.credit||0; } })); return Object.values(map); }
function openCostCenterModal(id){ const c=id?DB.get('costCenters').find(x=>x.id===id):null; openModal(t('مركز تكلفة','Cost Center'), `<div class="form-grid"><label>${t('الكود','Code')}<input id="ccCode" value="${esc(c?c.code:'')}"></label><label>${t('الاسم','Name')}<input id="ccName" value="${esc(c?c.name:'')}"></label></div>`, [{label:t('حفظ','Save'),cls:'btn-primary',onClick:()=>{ const name=$('#ccName').value.trim(); if(!name){toast(t('الاسم مطلوب','Name required'));return;} let list=DB.get('costCenters'); if(c) Object.assign(c,{code:$('#ccCode').value,name}); else list.push({id:uid(),code:$('#ccCode').value,name}); DB.set('costCenters',list); closeModal(); renderCostCentersScreen(); }},{label:t('إلغاء','Cancel'),cls:'btn',onClick:closeModal}]); }
function deleteCostCenter(id){ confirmModal(t('حذف','Delete'), t('حذف مركز التكلفة؟','Delete cost center?'), ()=>{ DB.set('costCenters',DB.get('costCenters').filter(x=>x.id!==id)); renderCostCentersScreen(); }); }
/* ============================ CLOSING ENTRIES ============================ */
function renderClosingScreen(){ ensurePeriods(); $('#screen').innerHTML=`<div class="screen"><div class="toolbar"><h2>${t('إقفال الفترة','Period Closing')}</h2></div>
  <p>${t('يقوم إقفال الفترة بترحيل أرصدة الإيرادات والمصروفات إلى حقوق الملكية (حساب الأرباح المرحلة)','Closing posts revenues & expenses to retained earnings')}</p>
  <label>${t('الفترة','Period')}<select id="closePer">${DB.get('periods').map(p=>`<option value="${p.code}">${esc(p.code)}</option>`).join('')}</select></label>
  <button class="btn btn-primary" style="margin-top:10px" onclick="doClosePeriod()">${t('ترحيل إقفال','Post Closing')}</button>
  <h3>${t('قيود الإقفال السابقة','Prior Closing Entries')}</h3><table class="tbl"><thead><tr><th>${t('الفترة','Period')}</th><th>${t('التاريخ','Date')}</th><th>${t('صافي الربح','Net')}</th></tr></thead><tbody>${DB.get('closings').map(c=>`<tr><td>${esc(c.period)}</td><td>${fmtDate(c.date)}</td><td>${money(c.net)}</td></tr>`).join('')}</tbody></table></div>`; applyLang(); }
function computeBalancesForPeriod(ym){ const accounts=DB.get('accounts'); const map={}; accounts.forEach(a=>map[a.id]=0); DB.get('journal').forEach(j=>{ if(periodOf(j.date)!==ym) return; if(j.status==='draft'||j.status==='pending') return; j.lines.forEach(l=>{ map[l.accountId]=(map[l.accountId]||0)+(Number(l.debit)||0)-(Number(l.credit)||0); }); }); return map; }
function doClosePeriod(){ const ym=$('#closePer').value; if(isPeriodLocked(ym)){ toast(t('الفترة مقفلة بالفعل','Already closed')); return; }
  if(DB.get('closings').some(c=>c.period===ym)){ toast(t('تم إقفال هذه الفترة مسبقاً','Already closed this period')); return; }
  const b=computeBalancesForPeriod(ym); const accounts=DB.get('accounts');
  const inc=accounts.filter(a=>a.type==='income').reduce((s,a)=>s-(b[a.id]||0),0);
  const exp=accounts.filter(a=>a.type==='expense').reduce((s,a)=>s+(b[a.id]||0),0);
  const net=inc-exp;
  const lines=[];
  accounts.filter(a=>a.type==='income').forEach(a=>{ if((b[a.id]||0)!==0) lines.push({accountId:a.id,debit:-(b[a.id]||0),credit:0}); });
  accounts.filter(a=>a.type==='expense').forEach(a=>{ if((b[a.id]||0)!==0) lines.push({accountId:a.id,debit:0,credit:(b[a.id]||0)}); });
  lines.push({accountId:'acc_retained',debit:net>=0?0:Math.abs(net),credit:net>=0?net:0});
  const J=DB.get('journal'); const d=new Date().toISOString().slice(0,10);
  J.push({id:uid(),code:nextNumber('JV','JV-',5),date:d,desc:t('إقفال','Closing')+' '+ym,lines:normalizeLines(lines),ref:'close_'+ym,status:'approved'});
  DB.set('journal',J);
  const closings=DB.get('closings'); closings.push({id:uid(),period:ym,date:d,net}); DB.set('closings',closings);
  lockPeriod(ym); renderClosingScreen(); logAudit(t('إقفال فترة','Close period'),ym+' '+money(net)); toast(t('تم الإقفال','Closed')+' '+money(net)); }
/* ============================ TRIAL BALANCE (filtered) ============================ */
function reportTrialBalanceRows(ym){ const accounts=DB.get('accounts'); const J=DB.get('journal').filter(j=>!ym||periodOf(j.date)===ym); const map={}; accounts.forEach(a=>map[a.id]=0);   J.forEach(j=>{ if(j.status==='draft'||j.status==='pending') return; j.lines.forEach(l=>{ map[l.accountId]=(map[l.accountId]||0)+(Number(l.debit)||0)-(Number(l.credit)||0); }); }); let td=0,tc=0; accounts.forEach(a=>{ const v=map[a.id]||0; td+=v>0?v:0; tc+=v<0?-v:0; }); return {rows:accounts.map(a=>({code:a.code,name:a.name,debit:map[a.id]>0?map[a.id]:0,credit:map[a.id]<0?-map[a.id]:0})), totalDebit:td, totalCredit:tc, unbalanced:Math.abs(td-tc)>0.01}; }
function reportTrialBalanceFull(){ const r=reportTrialBalanceRows(null); const rows=[['Code','Account','Debit','Credit']]; r.rows.forEach(a=>rows.push([a.code,a.name,fmt(a.debit),fmt(a.credit)])); rows.push(['','Total',fmt(r.totalDebit),fmt(r.totalCredit)]); downloadFile('trial_balance.csv',toCSV(rows),'text/csv'); exportPDF('trial_balance.pdf',[t('ميزان مراجعة','Trial Balance'),r.unbalanced?t('غير متوازن','UNBALANCED'):t('متوازن','Balanced'),...rows.map(x=>x.join('   '))]); toast(t('تم التصدير','Exported')); }
/* ============================ CASH FLOW STATEMENT ============================ */
function renderCashFlowScreen(){ const J=DB.get('journal').filter(j=>j.status==='approved'||j.status==='posted');   const cashAccs=new Set(DB.get('bankAccounts').map(b=>b.accountId).concat([CFG.ACC.CASH])); let op=0,inv=0,fin=0;
  J.forEach(j=>{ const hasCash=j.lines.some(l=>cashAccs.has(l.accountId)); if(!hasCash) return; const net=j.lines.reduce((s,l)=>DEC.add(s, DEC.sub(l.debit||0, l.credit||0)),0); const types=new Set(j.lines.map(l=>(DB.get('accounts').find(a=>a.id===l.accountId)||{}).type)); if(types.has('income')||types.has('expense')) op+=0; });
  /* Simplified: operating = net change in cash from P&L items; investing = fixed asset movements; financing = equity/liability */
  const b=computeBalances(); const accounts=DB.get('accounts');
  const startCash=0; /* opening not tracked separately here */
  let operating=0, investing=0, financing=0;
  J.forEach(j=>{ j.lines.forEach(l=>{ const acc=accounts.find(a=>a.id===l.accountId); if(!acc) return; const delta=(l.debit||0)-(l.credit||0);
    if(['income','expense'].includes(acc.type)) operating+=delta;
    else if(acc.id==='acc_fa'||acc.id==='acc_fa_dep') investing+=delta;
    else if(['liability','equity'].includes(acc.type)) financing+=delta;
    else if(cashAccs.has(acc.id)) {} /* cash to cash excluded */
  }); });
  const endCash=cashAccs.size?cashAccs.reduce((s,id)=>s+(b[id]||0),0):0;
  const lines=[t('التدفقات النقدية','Cash Flow Statement'), t('تشغيلي','Operating')+': '+money(operating), t('استثماري','Investing')+': '+money(investing), t('تمويلي','Financing')+': '+money(financing), t('صافي التغير','Net Change')+': '+money(operating+investing+financing), t('النقدية النهائية','Ending Cash')+': '+money(endCash)];
  $('#screen').innerHTML=`<div class="screen"><div class="toolbar"><h2>${t('التدفقات النقدية','Cash Flow')}</h2><button class="btn" onclick="exportCashFlow()">${t('تصدير','Export')}</button></div>
  <table class="tbl"><tbody>
   <tr><td>${t('أنشطة تشغيلية','Operating Activities')}</td><td>${money(operating)}</td></tr>
   <tr><td>${t('أنشطة استثمارية','Investing Activities')}</td><td>${money(investing)}</td></tr>
   <tr><td>${t('أنشطة تمويلية','Financing Activities')}</td><td>${money(financing)}</td></tr>
   <tr><td><b>${t('صافي التغير النقدي','Net Cash Change')}</b></td><td><b>${money(operating+investing+financing)}</b></td></tr>
   <tr><td><b>${t('النقدية النهائية','Ending Cash')}</b></td><td><b>${money(endCash)}</b></td></tr>
  </tbody></table></div>`; applyLang(); window._cashFlowLines=lines; }
function exportCashFlow(){ if(!window._cashFlowLines){ toast(t('لا بيانات','No data')); return; } exportPDF('cash_flow.pdf',window._cashFlowLines); toast(t('تم التصدير','Exported')); }
/* ============================ SEED DEFAULTS ============================ */
function seedAccountingDefaults(){ ensurePeriods(); ensureSeq(); ensureAssetAccount();
  if(!DB.get('costCenters').length) DB.set('costCenters',[{id:uid(),code:'CC-01',name:t('الإدارة','Administration')},{id:uid(),code:'CC-02',name:t('المبيعات','Sales')},{id:uid(),code:'CC-03',name:t('المخازن','Warehouse')}]);
  let accounts=DB.get('accounts');
  const ensure=(id,code,name,type,parent)=>{ if(!accounts.find(a=>a.id===id)){ accounts.push({id,code,name,type,parent:parent||null,balance:0}); } };
  ensure('acc_asset_root','1000',t('الأصول','Assets'),'asset',null);
  ensure('acc_liab_root','2000',t('الالتزامات','Liabilities'),'liability',null);
  ensure('acc_equity_root','3000',t('حقوق الملكية','Equity'),'equity',null);
  ensure('acc_income_root','4000',t('الإيرادات','Income'),'income',null);
  ensure('acc_expense_root','5000',t('المصروفات','Expenses'),'expense',null);
  ensure('acc_retained','3010',t('الأرباح المرحلة','Retained Earnings'),'equity','acc_equity_root');
  ensure('acc_depreciation_exp','5100',t('مصروف الإهلاك','Depreciation Expense'),'expense','acc_expense_root');
  DB.set('accounts',accounts);
  ensure('acc_bank','1003',t('البنك','Bank'),'asset','acc_asset_root');
  const banks=DB.get('bankAccounts'); if(banks.length && banks[0].accountId===CFG.ACC.CASH){ banks[0].accountId=CFG.ACC.BANK; DB.set('bankAccounts',banks); }
  if(!DB.get('bankStatements')) DB.set('bankStatements',[]);
  if(!DB.get('closings')) DB.set('closings',[]); }
